#properties
#sample #1
querySamples:
  assembly-id-1: GRCh37
  position-1: 179832996
  reference-name-1: 1
  alternate-bases-1: 
  dataset-ids-1: 
#sample #2
  assembly-id-2: GRCh37
  position-2: 179832996
  reference-name-2: 1
  alternate-bases-2: 
  dataset-ids-2: EGAD00001000741,EGAD00001000740
#sample #3
  assembly-id-3: GRCh37
  position-3: 179832996
  reference-name-3: 1
  alternate-bases-3: A
  dataset-ids-3: 
